name: Subscription form CI

on: [push]

jobs:
    build:

        runs-on: ubuntu-latest

        env:
            wp-plugin-directory: plugins/subscribe

        steps:
            -   name: Download Plugin
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    tools: pecl
                    php-version: 7.2

            -   name: Install dependencies
                run: |
                  composer install
                  npm install

            -   name: Run CS
                run: npm run cs
