name: Subscription form CI

on: [push]

jobs:
    build:

        runs-on: ubuntu-latest

        env:
            wp-plugin-directory: plugins/subscribe

        steps:
            -   name: Download Plugin
                uses: actions/checkout@v2
                with:
                    path: ${{ env.wp-plugin-directory }}

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    tools: pecl
                    php-version: 7.2
                env:
                    update: true

            -   name: Validate composer.json and composer.lock
                working-directory: ${{ env.wp-plugin-directory }}
                run: composer validate

            -   name: Install dependencies
                working-directory: ${{ env.wp-plugin-directory }}
                run: composer install

            -   name: Validate Coding Standard
                working-directory: ${{ env.wp-plugin-directory }}
                run: composer cs
